import { basename } from 'node:path'
import type { LoadedIndex } from '../core/types'
import { MCP_AGENT_RULE } from '../core/mcp-rules'

export const BEGIN = '<!-- claude-ctx:begin v1 -->'
export const END = '<!-- claude-ctx:end -->'

const RULES = [
  `- ${MCP_AGENT_RULE}`,
  '- Pick the tool: one symbol end-to-end → `mcp__ctx__trace_symbol` · its full body → `mcp__ctx__symbol_body` · its execution flow → `mcp__ctx__call_chain` · all usages → `mcp__ctx__references` (kind:"calls" for call-sites only) · find by name → `mcp__ctx__symbol_search` (not grep) · files for a task → `mcp__ctx__context_pack`.',
  '- Use `mcp__ctx__context_pack` first for multi-file work; `mcp__ctx__symbol_body` instead of re-Reading a file to see a whole function.',
  '- Check related tests before editing with `mcp__ctx__find_tests`.',
  '- Never edit generated/vendor files; confirm with the user before changing infra/prod-sensitive files.',
  '- Record decisions and next steps with `mcp__ctx__session_note`.',
  '- Tip: add `"mcp__ctx__*"` to `permissions.allow` in settings.json so these tools load without an approval prompt.',
]

export function renderManagedBlock(idx: LoadedIndex): string {
  const meta = idx.meta
  const lines: string[] = [BEGIN]
  lines.push('# Repo intelligence (generated by claude-ctx — do not edit this block)')
  lines.push('')
  lines.push(`**Project:** ${basename(meta.root)} — ${meta.projectType}, ${meta.fileCount} files`)
  if (meta.packages.length > 0) {
    lines.push(
      `**Packages:** ${meta.packages
        .slice(0, 8)
        .map((p) => `${p.name} (${p.dir || '.'})`)
        .join('; ')}`,
    )
  }
  const entries: string[] = []
  for (const p of meta.packages) for (const e of p.entrypoints) if (!entries.includes(e) && entries.length < 6) entries.push(e)
  if (entries.length > 0) lines.push(`**Entrypoints:** ${entries.join(', ')}`)
  const cmds = idx.commands.commands.slice(0, 6)
  if (cmds.length > 0) {
    lines.push('**Commands:**')
    for (const c of cmds) lines.push(`- \`${c.cmd}\` [${c.kind}]`)
  }
  lines.push('')
  lines.push('**Rules for this repo:**')
  for (const r of RULES) lines.push(r)
  // generated / infra path hints
  const gen = Object.entries(idx.files.files)
    .filter(([, r]) => r.risk.includes('generated'))
    .map(([p]) => p)
    .slice(0, 6)
  const infra = Object.entries(idx.files.files)
    .filter(([, r]) => r.risk.includes('infra'))
    .map(([p]) => p)
    .slice(0, 6)
  if (gen.length > 0) lines.push(`**Generated (do not edit):** ${gen.join(', ')}`)
  if (infra.length > 0) lines.push(`**Infra (confirm before changing):** ${infra.join(', ')}`)
  lines.push(END)
  return lines.join('\n')
}

/** Insert or replace the managed block; leave the rest of the file intact. */
export function upsertManagedBlock(existing: string | null, block: string): string {
  if (existing === null || existing.trim() === '') return block + '\n'
  const b = existing.indexOf(BEGIN)
  const e = existing.indexOf(END)
  if (b !== -1 && e !== -1 && e > b) {
    return existing.slice(0, b) + block + existing.slice(e + END.length)
  }
  return existing.trimEnd() + '\n\n' + block + '\n'
}
